apt-get install ffmpet

diff --git a/.github/workflows/jupyter-matrix.yml b/.github/workflows/jupyter-matrix.yml
--- a/.github/workflows/jupyter-matrix.yml
+++ b/.github/workflows/jupyter-matrix.yml
@@ -1,44 +1,44 @@
 name: jupyter-matrix
 on: push
 jobs:
-    list-notebooks:
-        runs-on: ubuntu-latest
-        outputs:
-            matrix: ${{ steps.set-matrix.outputs.matrix }}
-        steps:
-            - uses: actions/checkout@v4
-            - id: set-matrix
-              run: echo "matrix=$(find . -iwholename './tutorials/**/*.ipynb' -not -iname '*bose-hubbard*' -not -iwholename '*figures*' -printf '%P\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
-    notebook:
-        needs: list-notebooks
-        runs-on: ubuntu-latest
-        strategy:
-            fail-fast: false
-            matrix:
-                manifest: ${{ fromJson(needs.list-notebooks.outputs.matrix) }}
-        steps:
-            - uses: actions/checkout@v4
+  list-notebooks:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - uses: actions/checkout@v4
+      - id: set-matrix
+        run: echo "matrix=$(find . -iwholename './tutorials/**/*.ipynb' -not -iname '*bose-hubbard*' -not -iwholename '*figures*' -printf '%P\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
+  notebook:
+    needs: list-notebooks
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        manifest: ${{ fromJson(needs.list-notebooks.outputs.matrix) }}
+    steps:
+      - uses: actions/checkout@v4
 
-            - name: Install the latest version of uv
-              uses: astral-sh/setup-uv@v7
-              with:
-                  python-version: "3.13"
+      - name: Install the latest version of uv
+        uses: astral-sh/setup-uv@v7
+        with:
+          python-version: "3.13"
 
-            - name: Setup ffmpeg (with retries)
-              uses: ./.github/actions/setup-ffmpeg
+      - name: Install ffmpeg
+        run: sudo apt-get update && sudo apt-get install -y ffmpeg
 
-            - name: Setup TeX Live
-              uses: DanySK/setup-texlive-action@master
-              with:
-                  requirements-file: .github/texlive/requirements.txt
+      - name: Setup TeX Live
+        uses: DanySK/setup-texlive-action@master
+        with:
+          requirements-file: .github/texlive/requirements.txt
 
-            - name: Install Python dependencies
-              run: |
-                  uv sync --dev
+      - name: Install Python dependencies
+        run: |
+          uv sync --dev
 
-            - name: Build notebook
-              run: |
-                  uv run jupyter nbconvert --to notebook --inplace --execute --allow-errors "${{ matrix.manifest }}"
-                  TOTAL_ERRORS=0
-                  grep -q '"output_type": "error"' "${{ matrix.manifest }}" && echo "Found errors in ${{ matrix.manifest }}" && TOTAL_ERRORS=1 && printf '%b\n' | jq -r '.cells[].outputs[]?.traceback[]?' "${{ matrix.manifest }}"
-                  exit $TOTAL_ERRORS
+      - name: Build notebook
+        run: |
+          uv run jupyter nbconvert --to notebook --inplace --execute --allow-errors "${{ matrix.manifest }}"
+          TOTAL_ERRORS=0
+          grep -q '"output_type": "error"' "${{ matrix.manifest }}" && echo "Found errors in ${{ matrix.manifest }}" && TOTAL_ERRORS=1 && printf '%b\n' | jq -r '.cells[].outputs[]?.traceback[]?' "${{ matrix.manifest }}"
+          exit $TOTAL_ERRORS
