run  notebook

diff --git a/.github/workflows/jupyter-matrix.yml b/.github/workflows/jupyter-matrix.yml
--- a/.github/workflows/jupyter-matrix.yml
+++ b/.github/workflows/jupyter-matrix.yml
@@ -27,12 +27,5 @@ jobs:
           pip install -r requirements.txt
           pip install -r requirements_dev.txt
 
-      - run: echo "NOTEBOOK=${{ matrix.manifest }}" >> $GITHUB_ENV
-
-      - name: Build the books
-        run: |
-        echo "${{ env.NOTEBOOK }}"
-        # TOTAL_ERRORS=0
-        # jupyter nbconvert --to notebook --inplace --execute --allow-errors "${{ env.NOTEBOOK }}"
-        # grep -q '"output_type": "error"' "${{ env.NOTEBOOK }}" && echo "Found errors in ${{ env.NOTEBOOK }}" && TOTAL_ERRORS=1
-        # exit $TOTAL_ERRORS          
+      - run: jupyter nbconvert --to notebook --inplace --execute --allow-errors "${{ matrix.manifest }}"
+      # - run: grep -q '"output_type": "error"' "${{ matrix.manifest }}" && echo "Found errors in ${{ matrix.manifest }}" && exit 1      
