adjust grep again

diff --git a/.github/workflows/jupyter.yml b/.github/workflows/jupyter.yml
--- a/.github/workflows/jupyter.yml
+++ b/.github/workflows/jupyter.yml
@@ -24,9 +24,7 @@ jobs:
         TOTAL_ERRORS=0
         for nb in tutorials/**/*.ipynb; do
             jupyter-book build "$nb"
-            grep '"output_type": "error"' "$nb"; ERROR_COUNT=$? 
-            echo "Found $ERROR_COUNT in $nb"
-            TOTAL_ERRORS=$(($TOTAL_ERRORS + $ERROR_COUNT))
+            grep '"output_type": "error"' "$nb" || ERROR_COUNT=$? && echo "Found $ERROR_COUNT errors in $nb" && TOTAL_ERRORS=$(($TOTAL_ERRORS + $ERROR_COUNT))          
         done
         echo "$TOTAL_ERRORS total errors found"
         exit $TOTAL_ERRORS
